# Generated by Django 4.1 on 2022-08-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="thumbnails",
            new_name="thumbnail",
        ),
    ]
